server:
  port: 8080
email:
  subject: "Default Subject"
  message: "Default Message"
security:
  jwt:
    token:
      secret-key: ${HER_TECH_SECURITY_JWT_KEY}
      expire-length: 3600000
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    locale: pt_BR
    charset: UTF-8
  jackson:
    time-zone: America/Sao_Paulo
  messages:
    encoding: UTF-8
  application:
    name: Her Tech Rise API
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${HER_TECH_DATABASE_URL}
    username: ${HER_TECH_DATABASE_USERNAME}
    password: ${HER_TECH_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: America/Sao_Paulo
    show-sql: false
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${HER_TECH_EMAIL_USERNAME}
    password: ${HER_TECH_EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enabled: true
      mail.smtp.starttls.required: true
  flyway:
    baseline-on-migrate: true
logging:
  level:
    root: INFO